name: Run Pytest with Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-test-runner .

    - name: Run All Tests (Parallel)
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: reports/allure-report
